/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.view;

import br.com.ifba.aluno.view.TelaListagemAlunos;
import br.com.ifba.aluno.view.TelaMatriculaAlunos;
import br.com.ifba.instrutor.view.ListarInstrutorView;
import br.com.ifba.modalidade.view.ModalidadeView;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

/**
 *
 * @author João Victor
 */
@Component
@Slf4j
public class TelaMenuPrincipalRecepcionista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuPrincipalRecepcionista.class.getName());

    /**
     * Creates new form TelaMenuPrincipalRecepcionista
     */
    public TelaMenuPrincipalRecepcionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnMatricularAlunos = new javax.swing.JButton();
        btnInstrutores = new javax.swing.JButton();
        btnListarAlunos = new javax.swing.JButton();
        btnModalidades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU RECEPCIONISTA");

        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnMatricularAlunos.setText("MATRICULAR ALUNOS");
        btnMatricularAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularAlunosActionPerformed(evt);
            }
        });

        btnInstrutores.setText("INSTRUTORES");
        btnInstrutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstrutoresActionPerformed(evt);
            }
        });

        btnListarAlunos.setText("LISTAR ALUNOS");
        btnListarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAlunosActionPerformed(evt);
            }
        });

        btnModalidades.setText("MODALIDADES");
        btnModalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModalidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMatricularAlunos)
                    .addComponent(btnInstrutores)
                    .addComponent(btnListarAlunos)
                    .addComponent(btnModalidades))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSair)))
                .addGap(26, 26, 26)
                .addComponent(btnMatricularAlunos)
                .addGap(26, 26, 26)
                .addComponent(btnListarAlunos)
                .addGap(18, 18, 18)
                .addComponent(btnInstrutores)
                .addGap(18, 18, 18)
                .addComponent(btnModalidades)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        new TelaDeLogin().setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnMatricularAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularAlunosActionPerformed
        new TelaMatriculaAlunos().setVisible(true);
    }//GEN-LAST:event_btnMatricularAlunosActionPerformed

    private void btnListarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAlunosActionPerformed
        new TelaListagemAlunos().setVisible(true);
    }//GEN-LAST:event_btnListarAlunosActionPerformed

    private void btnInstrutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstrutoresActionPerformed
        new ListarInstrutorView().setVisible(true);
    }//GEN-LAST:event_btnInstrutoresActionPerformed

    private void btnModalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModalidadesActionPerformed
        new ModalidadeView().setVisible(true);
    }//GEN-LAST:event_btnModalidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenuPrincipalRecepcionista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInstrutores;
    private javax.swing.JButton btnListarAlunos;
    private javax.swing.JButton btnMatricularAlunos;
    private javax.swing.JButton btnModalidades;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
