/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.view;

import br.com.ifba.aluno.view.TelaListagemAlunos;
import br.com.ifba.instrutor.view.AdicionarInstrutorView;
import br.com.ifba.instrutor.view.ListarInstrutorView;
import br.com.ifba.pagamento.view.TelaRelatorioFinanceiro;
import br.com.ifba.recepcionista.controller.RecepcionistaIController;
import br.com.ifba.recepcionista.view.TelaCadastroRecepcionista;
import br.com.ifba.recepcionista.view.TelaListagemRecepcionista;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author João Victor
 */
@Component
@Slf4j
public class TelaMenuPrincipalAdm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuPrincipalAdm.class.getName());
    @Autowired
    private RecepcionistaIController recepcionistaController;
    
    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenuPrincipalAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAlunos = new javax.swing.JButton();
        btnCadRecep = new javax.swing.JButton();
        btnListRecep = new javax.swing.JButton();
        btnCadInst = new javax.swing.JButton();
        btnListInst = new javax.swing.JButton();
        btnFinanceiro = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU ADMINISTRADOR");

        btnAlunos.setText("ALUNOS");
        btnAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunosActionPerformed(evt);
            }
        });

        btnCadRecep.setText("CADASTRAR RECEPCIONISTA");
        btnCadRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadRecepActionPerformed(evt);
            }
        });

        btnListRecep.setText("LISTAR RECEPCIONISTAS");
        btnListRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListRecepActionPerformed(evt);
            }
        });

        btnCadInst.setText("CADASTRAR INSTRUTORES");
        btnCadInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadInstActionPerformed(evt);
            }
        });

        btnListInst.setText("LISTAR INSTRUTORES");
        btnListInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListInstActionPerformed(evt);
            }
        });

        btnFinanceiro.setText("FINANCEIRO");
        btnFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceiroActionPerformed(evt);
            }
        });

        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAlunos))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCadRecep))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnListRecep))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCadInst))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnListInst))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnFinanceiro)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSair))
                .addGap(18, 18, 18)
                .addComponent(btnAlunos)
                .addGap(18, 18, 18)
                .addComponent(btnCadRecep)
                .addGap(18, 18, 18)
                .addComponent(btnListRecep)
                .addGap(18, 18, 18)
                .addComponent(btnCadInst)
                .addGap(18, 18, 18)
                .addComponent(btnListInst)
                .addGap(18, 18, 18)
                .addComponent(btnFinanceiro)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunosActionPerformed
        new TelaListagemAlunos().setVisible(true);
    }//GEN-LAST:event_btnAlunosActionPerformed

    private void btnCadRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadRecepActionPerformed
        new TelaCadastroRecepcionista(this.recepcionistaController).setVisible(true);
    }//GEN-LAST:event_btnCadRecepActionPerformed

    private void btnListRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListRecepActionPerformed
        new TelaListagemRecepcionista().setVisible(true);
    }//GEN-LAST:event_btnListRecepActionPerformed

    private void btnCadInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadInstActionPerformed
        new AdicionarInstrutorView().setVisible(true);
    }//GEN-LAST:event_btnCadInstActionPerformed

    private void btnListInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListInstActionPerformed
        new ListarInstrutorView().setVisible(true);
    }//GEN-LAST:event_btnListInstActionPerformed

    private void btnFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceiroActionPerformed
        new TelaRelatorioFinanceiro().setVisible(true);
    }//GEN-LAST:event_btnFinanceiroActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        new TelaDeLogin().setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenuPrincipalAdm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlunos;
    private javax.swing.JButton btnCadInst;
    private javax.swing.JButton btnCadRecep;
    private javax.swing.JButton btnFinanceiro;
    private javax.swing.JButton btnListInst;
    private javax.swing.JButton btnListRecep;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
