/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.manutencao.view;

import br.com.ifba.manutencao.controller.ManutencaoController;
import br.com.ifba.manutencao.entity.Manutencao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

/**
 *
 * @author ricley
 */
@Component
@Lazy
public class TelaManutencao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaManutencao.class.getName());

    @Autowired
    private ManutencaoController manutencaoController;
    @Autowired
    private TelaRelatorioManutencao telaRelatorio;
    
    public TelaManutencao() {
        initComponents();
        this.setResizable(false);
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        
    }
    
     // Executa após todas as injeções do Spring
    @jakarta.annotation.PostConstruct
    public void init() {
        atualizarTabela();
        
        if (telaRelatorio != null) {
        telaRelatorio.atualizar(); // garante que tabela do relatório está pronta
    }
    }
    
    // Atualiza a tabela com as manutenções cadastradas
    public void atualizarTabela() {
        List<Manutencao> lista = manutencaoController.findAll();

        DefaultTableModel modelo =
                (DefaultTableModel) tblEquipamento.getModel();

        modelo.setNumRows(0);

        for (Manutencao m : lista) {
            modelo.addRow(new Object[]{
                m.getId(),
                m.getNomeEquipamento(),
                m.getDescricaoProblema(),
                m.getStatus()
            });
        }
    }
    
    private void carregarCamposDaTabela() {
    int linha = tblEquipamento.getSelectedRow();

    if (linha != -1) {
        txtEquipamento.setText(
            tblEquipamento.getValueAt(linha, 1).toString()
        );

        txtDescricao.setText(
            tblEquipamento.getValueAt(linha, 2).toString()
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEquipamento = new javax.swing.JTextField();
        btnReportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEquipamento = new javax.swing.JTable();
        btnConcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Equipamento:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Controle de Manutencao");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Problema:");

        btnReportar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReportar.setText("Reportar");
        btnReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportarActionPerformed(evt);
            }
        });

        tblEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Descrição", "Status"
            }
        ));
        tblEquipamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEquipamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEquipamento);

        btnConcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConcluir.setText("Concluir Manutencao");
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane2.setViewportView(txtDescricao);

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRelatorio.setText("Exibir Relatorio");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnConcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2)))
                        .addGap(41, 41, 41)
                        .addComponent(btnReportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluir)
                            .addComponent(btnEditar))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRelatorio)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReportar))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConcluir)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnExcluir)
                        .addGap(50, 50, 50)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(btnRelatorio)
                        .addGap(78, 78, 78))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Ação do botão Reportar
    private void btnReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportarActionPerformed
        // TODO add your handling code here:
        
        String equipamento = txtEquipamento.getText();
        String descricao = txtDescricao.getText();
        
        // Validação simples dos campos
        if(equipamento.isEmpty() || descricao.isEmpty()){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            return;
        }
        
        // Chama o controller para salvar a manutenção
        manutencaoController.reportarProblema(equipamento, descricao);
        atualizarTabela();
        
        // Limpa os campos
         txtEquipamento.setText("");
         txtDescricao.setText("");

            JOptionPane.showMessageDialog(this, "Manutenção registrada com sucesso!");
                
    }//GEN-LAST:event_btnReportarActionPerformed

    // Ação do botão Excluir
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
        int linha = tblEquipamento.getSelectedRow();

    if (linha == -1) {
        JOptionPane.showMessageDialog(this, "Selecione uma manutenção na tabela.");
        return;
    }

    Long id = (Long) tblEquipamento.getValueAt(linha, 0);

    int confirmar = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente excluir a manutenção ID: " + id + "?",
            "Confirmar Exclusão",
            JOptionPane.YES_NO_OPTION
    );

    if (confirmar == JOptionPane.YES_OPTION) {
        try {
            manutencaoController.delete(id);
            atualizarTabela();
            JOptionPane.showMessageDialog(this, "Manutenção excluída com sucesso!");
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    }//GEN-LAST:event_btnExcluirActionPerformed

    // Ação do botão Editar
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
        int linha = tblEquipamento.getSelectedRow();

    if (linha == -1) {
        JOptionPane.showMessageDialog(this, "Selecione uma manutenção na tabela.");
        return;
    }

    if (txtEquipamento.getText().isEmpty() || txtDescricao.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha os campos antes de editar.");
        return;
    }

    Long id = (Long) tblEquipamento.getValueAt(linha, 0);

    try {
        // BUSCA a manutenção existente no banco
        Manutencao manutencao = manutencaoController.findById(id);

        // Atualiza SOMENTE os campos editáveis
        manutencao.setNomeEquipamento(txtEquipamento.getText());
        manutencao.setDescricaoProblema(txtDescricao.getText());

        // Salva mantendo custo, status e data
        manutencaoController.update(manutencao);

        atualizarTabela();
        JOptionPane.showMessageDialog(this, "Manutenção atualizada com sucesso!");

    } catch (RuntimeException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    // Ação do botão Concluir Manutenção
    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        // TODO add your handling code here:
        
       int linha = tblEquipamento.getSelectedRow();

        if (linha == -1) {
        JOptionPane.showMessageDialog(this, "Selecione uma manutenção na tabela.");
        return;
    }

        Long id = (Long) tblEquipamento.getValueAt(linha, 0);

        try {
            //Busca a manutenção real no banco
            Manutencao manutencao = manutencaoController.findById(id);

            //BLOQUEIA se já estiver concluída
            if ("CONCLUÍDA".equalsIgnoreCase(manutencao.getStatus())) {
            JOptionPane.showMessageDialog(
                this,
                "Esta manutenção já foi concluída.",
                "Ação inválida",
                JOptionPane.WARNING_MESSAGE
            );
                return;
        }

            //Só aqui pede o custo
            String custoStr = JOptionPane.showInputDialog(
                this,
                "Informe o custo da manutenção:"
        );

            if (custoStr == null || custoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Custo é obrigatório!");
            return;
        }

         double custo;
            try {
            custo = Double.parseDouble(custoStr.replace(",", "."));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Informe um valor numérico válido!");
            return;
        }

        //Conclui de verdade
        manutencao.setCusto(custo);
        manutencao.setStatus("CONCLUÍDA");
        manutencao.setDataReporte(java.time.LocalDate.now());

        manutencaoController.update(manutencao);

        atualizarTabela();
        JOptionPane.showMessageDialog(this, "Manutenção concluída com sucesso!");

    } catch (RuntimeException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnConcluirActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        // Pega todas as manutenções
        List<Manutencao> manutencoes = manutencaoController.findAll();

        // Filtra apenas as concluídas
        boolean existeConcluida = manutencoes.stream()
            .anyMatch(m -> "CONCLUÍDA".equalsIgnoreCase(m.getStatus()));

        if (!existeConcluida) {
            // Se não houver nenhuma concluída, mostra mensagem
            JOptionPane.showMessageDialog(this, 
            "Nenhuma manutenção concluída para exibir!",
            "Relatório Vazio",
            JOptionPane.WARNING_MESSAGE);
         return;
    }   

        // Atualiza a tabela do relatório
        telaRelatorio.atualizar();

        // Mostra a tela de relatório
         this.setVisible(false);
        telaRelatorio.setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void tblEquipamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEquipamentoMouseClicked
        // TODO add your handling code here:
        int linha = tblEquipamento.getSelectedRow();

        if (linha != -1) {
        txtEquipamento.setText(
        tblEquipamento.getValueAt(linha, 1).toString()
    );

        txtDescricao.setText(
        tblEquipamento.getValueAt(linha, 2).toString()
    );
}
    }//GEN-LAST:event_tblEquipamentoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcluir;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnReportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEquipamento;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtEquipamento;
    // End of variables declaration//GEN-END:variables
}
