/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.pagamento.view;

import br.com.ifba.dto.DadosFinanceiro;
import br.com.ifba.pagamento.service.PagamentoService;
import javax.swing.JOptionPane;


/**
 *
 * @author ETM-00168
 */
public class telaPagamento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaPagamento.class.getName());

    private final PagamentoService pagamentoService = new PagamentoService();
    
    /**
     * Creates new form Pagamento
     */
    public telaPagamento() {
        initComponents();
         // Importante: Não matar o app ao fechar esta janela
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblPlano = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela Pagamento");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("CPF");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 42, 47, 22));

        txtCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCpf.setText("...");

        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 43, 106, -1));


        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 104, -1, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Plano atual:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Valor a pagar:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 188, -1, -1));

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("0");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 108, 158, -1));

        lblPlano.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPlano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlano.setText("0");
        getContentPane().add(lblPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 150, 158, -1));

        lblValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValor.setText("0");
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 188, 158, -1));

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("Registrar Pagamento");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 243, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void buscarAluno() {

    String cpf = txtCpf.getText();

    try {
        DadosFinanceiro dados =
                pagamentoService.buscarDadosFinanceiros(cpf);

        // Se achou aluno, mostra os dados
        lblNome.setText(dados.getNomeAluno());
        lblPlano.setText("Plano Padrão");
        lblValor.setText(String.valueOf(dados.getValor()));

    } catch (RuntimeException e) {

        // Se NÃO achou aluno
        if ("ALUNO_NAO_ENCONTRADO".equals(e.getMessage())) {

            JOptionPane.showMessageDialog(
                    null,
                    "Aluno não encontrado",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );

            // Limpa os campos
            lblNome.setText("");
            lblPlano.setText("");
            lblValor.setText("");
        }
    }
}
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
        buscarAluno();
    }//GEN-LAST:event_btnBuscarActionPerformed

    
    public void registrarPagamento() {

        String cpf = txtCpf.getText();
        pagamentoService.registrarPagamento(cpf);

        JOptionPane.showMessageDialog(
        null,
        "Pagamento registrado com sucesso!",
        "Sucesso",
        JOptionPane.INFORMATION_MESSAGE
);
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
     registrarPagamento();
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPlano;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtCpf;
    // End of variables declaration//GEN-END:variables
}
