/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.turma.view;

import br.com.ifba.turma.entity.Turma;
import br.com.ifba.turma.repository.TurmaRepository;
import java.awt.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angra
 */
public class TurmaView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TurmaView.class.getName());

    /**
     * Creates new form TurmaView
     */
    public TurmaView() {
        initComponents();
        //carregarTurma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListarTurma = new javax.swing.JTable();
        btnExcluirTurma = new javax.swing.JButton();
        txtPesquisarId = new java.awt.TextField();
        btnPesquisar = new javax.swing.JButton();
        btnAdicionarTurma = new javax.swing.JButton();
        btnEditarTurma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaListarTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null,  new Boolean(false)},
                {null, null, null, null, null, null,  new Boolean(false)}
            },
            new String [] {
                "Id", "Nome", "Id Instrutor", "Id Modalidade", "Horário", "Capacidade", "Selecionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaListarTurma.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tabelaListarTurma);
        tabelaListarTurma.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btnExcluirTurma.setText("Excluir");
        btnExcluirTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTurmaActionPerformed(evt);
            }
        });

        txtPesquisarId.setText("Pesquisar");
        txtPesquisarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarIdActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon("C:\\Users\\angra\\Documents\\NetBeansProjects\\prog03presistencia\\src\\main\\resources\\META-INF\\imagens\\lupa.png")); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAdicionarTurma.setText("Adicionar");
        btnAdicionarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarTurmaActionPerformed(evt);
            }
        });

        btnEditarTurma.setText("Editar");
        btnEditarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisarId, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarTurma)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarTurma)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirTurma))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluirTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdicionarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisarId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void carregarTurma() {
//        DefaultTableModel tabela = (DefaultTableModel) tabelaListarTurma.getModel();
//        tabela.setNumRows(0);
//
//        TurmaRepository turmaRepository;
//        turmaRepository = new TurmaRepository() {};
//      
//        try {
//            for(Turma turma : turmaRepository.findAll()) {
//                tabela.addRow(new Object[]{
//                    turma.getId(),
//                    turma.getNome(),
//                    turma.getInstrutor(),
//                    turma.getModalidade(),
//                    turma.getHorario(),
//                    turma.getCapacidade()
//                });
//            } 
//        } catch(Exception Erro) {
//            JOptionPane.showMessageDialog(
//                    null, 
//                    "Erro ao carregar a turma\n" + Erro, 
//                    "ERRO", 
//                    JOptionPane.ERROR_MESSAGE
//            );
//        }
    }
    
    private void btnExcluirTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTurmaActionPerformed
        // TODO add your handling code here:

//        if(tabelaListarTurma.getSelectedRow() != -1) {
//            int resposta = JOptionPane.showConfirmDialog(
//                null,
//                "Excluir o curso selecionado?",
//                "Excluir curso",
//                JOptionPane.YES_NO_OPTION
//            );
//
//            if(resposta == JOptionPane.YES_OPTION) {
//                Long id = (Long) tabelaListarTurma.getValueAt(tabelaListarTurma.getSelectedRow(), 1);
//
//                TurmaRepository turmaRepository = new TurmaRepository;
//                turmaRepository.delete(id);
//
//                //carregarCursos();
//            }
//        } else {
//            JOptionPane.showMessageDialog(
//                null,
//                "Selecione uma turma"
//            );
//        }
    }//GEN-LAST:event_btnExcluirTurmaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAdicionarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTurmaActionPerformed
        // TODO add your handling code here:
        TurmaAdicionarView adicionarTurma = new TurmaAdicionarView();
        adicionarTurma.setVisible(true);
    }//GEN-LAST:event_btnAdicionarTurmaActionPerformed

    private void btnEditarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTurmaActionPerformed
        if(tabelaListarTurma.getSelectedRow() != -1) {
            //Guarda o id do curso selecionado e envia para a tela cursoEditar
            Long id = (Long) tabelaListarTurma.getValueAt(tabelaListarTurma.getSelectedRow(), 1);
            TurmaEditarView editarTurma = new TurmaEditarView(this, id);
            editarTurma.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(
                null,
                "Selecione um curso"
            );
        }
    }//GEN-LAST:event_btnEditarTurmaActionPerformed

    private void txtPesquisarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TurmaView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarTurma;
    private javax.swing.JButton btnEditarTurma;
    private javax.swing.JButton btnExcluirTurma;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaListarTurma;
    private java.awt.TextField txtPesquisarId;
    // End of variables declaration//GEN-END:variables
}
