/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.administrador.view;

import br.com.ifba.administrador.entity.Administrador;
import br.com.ifba.endereco.entity.Endereco;
import br.com.ifba.usuario.entity.Usuario;
import br.com.ifba.usuario.enums.PerfilUsuarioEnums;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

/**
 *
 * @author João Victor
 */
@Component
@Slfj4
public class TelaAdministrador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAdministrador.class.getName());

    @org.springframework.beans.factory.annotation.Autowired
    private br.com.ifba.administrador.controller.AdministradorController administradorController;

    private javax.swing.table.DefaultTableModel modeloTabela;
    /**
     * Creates new form TelaAdministrador
     */
    public TelaAdministrador() {
        initComponents();
        modeloTabela = (javax.swing.table.DefaultTableModel) tblAdministrador.getModel();
        tblAdministrador.setEnabled(true); // Permite selecionar a linha
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdministrador = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAdministrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "NOME", "TELEFONE", "NASCIMENTO", "EMAIL", "ENDEREÇO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAdministrador);

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR POR CPF");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnExcluir)
                    .addComponent(btnBuscar)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
        
        String novoCpf = javax.swing.JOptionPane.showInputDialog(this, "CPF do administrador:");
        if (novoCpf == null) return;

        String novoNome = javax.swing.JOptionPane.showInputDialog(this, "Nome do administrador:");
        if (novoNome == null) return;

        String novoTelefone = JOptionPane.showInputDialog(this, "Telefone:");
        if (novoTelefone == null) return;

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dataStr = JOptionPane.showInputDialog(this, "Data de Nascimento (dd/MM/yyyy):");
        if (dataStr == null) return;

        LocalDate novaDataNascimento;
        try {
            novaDataNascimento = LocalDate.parse(dataStr, formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this,
                "Data inválida. Use o formato dd/MM/yyyy.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
        return;
        }

        String novoEmail = JOptionPane.showInputDialog(this, "Altura (cm):");
        if (novoEmail == null) return;

        String cidade = JOptionPane.showInputDialog(this, "Cidade:");
        if (cidade == null) return;

        String bairro = JOptionPane.showInputDialog(this, "Bairro:");
        if (bairro == null) return;

        String rua = JOptionPane.showInputDialog(this, "Rua:");
        if (rua == null) return;

        String novoNumeroStr = JOptionPane.showInputDialog(this, "Altura (cm):");
        if (novoNumeroStr == null) return;

        int numero;
        try {
            numero = Integer.parseInt(novoNumeroStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        String cep = JOptionPane.showInputDialog(this, "CEP:");
        if (cep == null) return;

        String complemento = JOptionPane.showInputDialog(this, "Complemento:");
        if (complemento == null) return;

        Endereco novoEndereco = new Endereco(
        cidade,
        bairro,
        rua,
        numero,
        cep,
        complemento
        );
        
        String login = JOptionPane.showInputDialog(this, "Login:");
        if (login == null) return;

        String senha = JOptionPane.showInputDialog(this, "Senha:");
        if (senha == null) return;

        String funcao = JOptionPane.showInputDialog(this, "Função:");
        if (funcao == null) return;

        Usuario dadosLogin = new Usuario(login, senha, funcao);

        // Declara uma variavel "e" do tipo Administrador
        Administrador e = new Administrador();
        
                e.setCpf(novoCpf);
                e.setNome(novoNome);
                e.setTelefone(novoTelefone);
                e.setNascimento(novaDataNascimento);
                e.setEmail(novoEmail);
                e.setEndereco(novoEndereco);
                e.setDadosLogin(dadosLogin);
                e.setPerfil(PerfilUsuarioEnums.ADMIN);

        administradorController.save(e);

        // 5. Sucesso e atualização da tela
        javax.swing.JOptionPane.showMessageDialog(this, "Administrador cadastrado com sucesso!");
        atualizarTabela();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + e.getMessage());
     }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //Verifica se tem alguma linha selecionada
    int linhaSelecionada = tblAdministrador.getSelectedRow();
    
    if (linhaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um administrador na tabela para excluir.");
        return;
    }

    //Pega o cpf da primeira coluna (coluna 0)
    String cpf = (String) modeloTabela.getValueAt(linhaSelecionada, 0);

    //Pergunta se tem certeza
    int resposta = javax.swing.JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o administrador CPF: " + cpf + "?");
    
    if (resposta == javax.swing.JOptionPane.YES_OPTION) {
        try {
            administradorController.deleteByCpf(cpf); // Chama o controller
            javax.swing.JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
            atualizarTabela(); // Atualiza a lista automaticamente
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // 1. Abre uma caixinha para o usuário digitar o CPF
    String cpfDigitado = javax.swing.JOptionPane.showInputDialog(this, "Digite o CPF do Administrador:");

    if (cpfDigitado != null && !cpfDigitado.trim().isEmpty()) {
        try {
            // 2. Busca Administrador via Controller
            br.com.ifba.administrador.entity.Administrador e = administradorController.findByCpf(cpfDigitado);

            if (e != null) {
                // 3. Limpa a tabela e mostra apenas o resultado encontrado
                modeloTabela.setNumRows(0);
                modeloTabela.addRow(new Object[]{
                e.getCpf(),
                e.getNome(),
                e.getTelefone(),
                e.getNascimento(),
                e.getEmail(),
                e.getEndereco()
                });
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Administrador não encontrado!");
            }
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao buscar: " + ex.getMessage());
        }
    } else if (cpfDigitado != null) {
        // Se o usuário clicou OK sem digitar nada, voltamos a listar todos
        atualizarTabela();
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // 1. Verifica se tem alguém selecionado
    int linhaSelecionada = tblAdministrador.getSelectedRow();
    
    if (linhaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um campo na tabela para editar.");
        return;
    }

    // 2. Pega a matricula e os dados atuais da tabela
    String cpf = (String) modeloTabela.getValueAt(linhaSelecionada, 0);
    String nome = (String) modeloTabela.getValueAt(linhaSelecionada, 1);
    String telefone = (String) modeloTabela.getValueAt(linhaSelecionada, 2);
    LocalDate nascimento = (LocalDate) modeloTabela.getValueAt(linhaSelecionada, 3);
    String email = (String) modeloTabela.getValueAt(linhaSelecionada, 4);
    Endereco endereco = (Endereco) modeloTabela.getValueAt(linhaSelecionada, 5);
    
     try {
        
        String novoCpf = javax.swing.JOptionPane.showInputDialog(this, "CPF do administrador:", cpf);
        if (novoCpf == null) return;

        String novoNome = javax.swing.JOptionPane.showInputDialog(this, "Nome do administrador:", nome);
        if (novoNome == null) return;

        String novoTelefone = JOptionPane.showInputDialog(this, "Telefone:", telefone);
        if (novoTelefone == null) return;

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dataStr = JOptionPane.showInputDialog(this, "Data de Nascimento (dd/MM/yyyy):", nascimento);
        if (dataStr == null) return;

        LocalDate novaDataNascimento;
        try {
            novaDataNascimento = LocalDate.parse(dataStr, formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this,
                "Data inválida. Use o formato dd/MM/yyyy.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
        return;
        }

        String novoEmail = JOptionPane.showInputDialog(this, "Email:", email);
        if (novoEmail == null) return;

        String cidade = JOptionPane.showInputDialog(this, "Cidade:", endereco.getCidade());
        if (cidade == null) return;

        String bairro = JOptionPane.showInputDialog(this, "Bairro:", endereco.getBairro());
        if (bairro == null) return;

        String rua = JOptionPane.showInputDialog(this, "Rua:", endereco.getCidade());
        if (rua == null) return;

        String novoNumeroStr = JOptionPane.showInputDialog(this, "Numero:", endereco.getNumero());
        if (novoNumeroStr == null) return;

        int numero;
        try {
            numero = Integer.parseInt(novoNumeroStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        String cep = JOptionPane.showInputDialog(this, "CEP:", endereco.getCep());
        if (cep == null) return;

        String complemento = JOptionPane.showInputDialog(this, "Complemento:", endereco.getComplemento());
        if (complemento == null) return;

        Endereco novoEndereco = new Endereco(
        cidade,
        bairro,
        rua,
        numero,
        cep,
        complemento
        );

        // Declara uma variavel "e" do tipo Administrador
        Administrador e = new Administrador();
        
                e.setCpf(novoCpf);
                e.setNome(novoNome);
                e.setTelefone(novoTelefone);
                e.setNascimento(novaDataNascimento);
                e.setEmail(novoEmail);
                e.setEndereco(novoEndereco);

        administradorController.update(e.getCpf(), e);

        // 5. Sucesso e atualização da tela
        javax.swing.JOptionPane.showMessageDialog(this, "Administrador atualizado com sucesso!");
        atualizarTabela();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage());
     }
    }//GEN-LAST:event_btnEditarActionPerformed

    //Método para mostrar a tabela de avaliação fisica
    public javax.swing.JTable getTabela() {
    return tblAdministrador;
}

    public void atualizarTabela() {
    // Limpa a tabela antes de carregar
    modeloTabela.setNumRows(0);
    
   try {
        // Busca a lista no banco via controller
        java.util.List<br.com.ifba.administrador.entity.Administrador> lista = administradorController.findAll();
        
        // Adiciona cada exercício como uma linha na tabela
        for (br.com.ifba.administrador.entity.Administrador e : lista) {
            modeloTabela.addRow(new Object[]{
                e.getCpf(),
                e.getNome(),
                e.getTelefone(),
                e.getNascimento(),
                e.getEmail(),
                e.getEndereco(),
                
            });
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar administradores: " + e.getMessage());
    }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAdministrador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAdministrador;
    // End of variables declaration//GEN-END:variables
}
