/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.avaliacaofisica.view;

import br.com.ifba.avaliacaofisica.entity.AvaliacaoFisica;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.springframework.stereotype.Component;

/**
 *
 * @author João Victor
 */
@Component
public class TelaAvaliacaoFisicaListar extends javax.swing.JFrame {
    
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAvaliacaoFisicaListar.class.getName());
    
    @org.springframework.beans.factory.annotation.Autowired
    private br.com.ifba.avaliacaofisica.controller.AvaliacaoFisicaController avaliacaoFisicaController;
    
    @org.springframework.beans.factory.annotation.Autowired
    private br.com.ifba.aluno.controller.AlunoController alunoController;

    private javax.swing.table.DefaultTableModel modeloTabela;
    
    public TelaAvaliacaoFisicaListar() {
        initComponents();
        modeloTabela = (javax.swing.table.DefaultTableModel) tblAvaliacaoFisica.getModel();
        tblAvaliacaoFisica.setEnabled(true); // Permite selecionar a linha
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblAvaliacaoFisica = new javax.swing.JTable();
        btnNovaAvlFis = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnBusMat = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAvaliacaoFisica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ALUNO", "INSTRUTOR", "DATA DA AVALIAÇÃO", "PESO", "ALTURA", "PERCENTUAL DE GORDURA", "BICEPS", "CINTURA", "OMBRO", "PANTURRILHA", "COXA", "GLUTEO", "PEITORAL", "IMC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAvaliacaoFisica.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblAvaliacaoFisica);

        btnNovaAvlFis.setText("NOVA AVALIAÇÃO FISICA");
        btnNovaAvlFis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaAvlFisActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnBusMat.setText("BUSCAR PELA MATRICULA");
        btnBusMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusMatActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNovaAvlFis, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBusMat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNovaAvlFis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBusMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //Verifica se tem alguma linha selecionada
    int linhaSelecionada = tblAvaliacaoFisica.getSelectedRow();
    
    if (linhaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma avaliação fisica na tabela para excluir.");
        return;
    }

    //Pega o ID da primeira coluna (coluna 0)
    String matricula = (String) modeloTabela.getValueAt(linhaSelecionada, 0);

    //Pergunta se tem certeza
    int resposta = javax.swing.JOptionPane.showConfirmDialog(this, "Deseja realmente excluir a avaliação fisica MATRICULA: " + matricula + "?");
    
    if (resposta == javax.swing.JOptionPane.YES_OPTION) {
        try {
            avaliacaoFisicaController.deleteByMatricula(matricula); // Chama o controller
            javax.swing.JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
            atualizarTabela(); // Atualiza a lista automaticamente
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovaAvlFisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaAvlFisActionPerformed
       try {
        //Abre caixinhas pedindo as novas informações (já sugere o nome atual)
        
        String novaMatricula = javax.swing.JOptionPane.showInputDialog(this, "Matricula do aluno:");
        if (novaMatricula == null) return; // Se cancelar, para aqui
        
        //Deve existir um aluno com a matricula informada para cadastrar a avaliação fisica
        if (!alunoController.existsByMatricula(novaMatricula)) {
            JOptionPane.showMessageDialog(this,
                "Matrícula não encontrada!",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String novoInstrutor = javax.swing.JOptionPane.showInputDialog(this, "Nome do Instrutor:");
        if (novoInstrutor == null) return;

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dataStr = JOptionPane.showInputDialog(this, "Data da Avaliação (dd/MM/yyyy):");
        if (dataStr == null) return;

        LocalDate novaDataAvaliacao;
        try {
            novaDataAvaliacao = LocalDate.parse(dataStr, formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this,
                "Data inválida. Use o formato dd/MM/yyyy.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
        return;
        }

        String novoPesoStr = JOptionPane.showInputDialog(this, "Peso:");
        if (novoPesoStr == null) return;

        float novoPeso;
        try {
            novoPeso = Float.parseFloat(novoPesoStr.replace(",", "."));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Peso inválido. Informe um número válido.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        String novaAlturaStr = JOptionPane.showInputDialog(this, "Altura (cm):");
        if (novaAlturaStr == null) return;

        int novaAltura;
        try {
            novaAltura = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String novoPercentualGorduraStr = JOptionPane.showInputDialog(this, "Percentual de gordura:");
        if (novoPercentualGorduraStr == null) return;

        float novoPercentualGordura;
        try {
            novoPercentualGordura = Float.parseFloat(novoPesoStr.replace(",", "."));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Percentual de gordura inválido. Informe um número válido.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        String novoBicepsStr = JOptionPane.showInputDialog(this, "Biceps:");
        if (novoBicepsStr == null) return;

        int novoBiceps;
        try {
            novoBiceps = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String novaCinturaStr = JOptionPane.showInputDialog(this, "Cintura:");
        if (novaCinturaStr == null) return;

        int novaCintura;
        try {
            novaCintura = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String novoOmbroStr = JOptionPane.showInputDialog(this, "Ombro:");
        if (novoOmbroStr == null) return;

        int novoOmbro;
        try {
            novoOmbro = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        String novaPanturrilhaStr = JOptionPane.showInputDialog(this, "Panturrilha:");
        if (novaPanturrilhaStr == null) return;

        int novaPanturrilha;
        try {
            novaPanturrilha = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        String novaCoxaStr = JOptionPane.showInputDialog(this, "Coxa:");
        if (novaCoxaStr == null) return;

        int novaCoxa;
        try {
            novaCoxa = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        String novoGluteoStr = JOptionPane.showInputDialog(this, "Gluteo:");
        if (novoGluteoStr == null) return;

        int novoGluteo;
        try {
            novoGluteo = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        String novoPeitoralStr = JOptionPane.showInputDialog(this, "Peitoral:");
        if (novoPeitoralStr == null) return;

        int novoPeitoral;
        try {
            novoPeitoral = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Declara uma variavel "e" do tipo AvaliacaoFisica
        AvaliacaoFisica e = new AvaliacaoFisica();
        
        e.getAluno().setMatricula(novaMatricula);
        e.getInstrutor().setName(novoInstrutor);
        e.setDataAvaliacao(novaDataAvaliacao);
        e.setPeso(novoPeso);
        e.setAltura(novaAltura);
        e.setPercentualGordura(novoPercentualGordura);
        e.setBiceps(novoBiceps);
        e.setCintura(novaCintura);
        e.setOmbro(novoOmbro);
        e.setPanturrilha(novaPanturrilha);
        e.setCoxa(novaCoxa);
        e.setGluteo(novoGluteo);
        e.setPeitoral(novoPeitoral);

        avaliacaoFisicaController.save(e);

        // 5. Sucesso e atualização da tela
        javax.swing.JOptionPane.showMessageDialog(this, "Avaliação cadastrada com sucesso!");
        atualizarTabela();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + e.getMessage());
     }
    }//GEN-LAST:event_btnNovaAvlFisActionPerformed

    private void btnBusMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusMatActionPerformed
        // 1. Abre uma caixinha para o usuário digitar a matricula
    String matDigitada = javax.swing.JOptionPane.showInputDialog(this, "Digite a matricula do Aluno:");

    if (matDigitada != null && !matDigitada.trim().isEmpty()) {
        try {
            // 2. Busca a avaliação fisica via Controller
            br.com.ifba.avaliacaofisica.entity.AvaliacaoFisica e = avaliacaoFisicaController.findByAluno_Matricula(matDigitada);

            if (e != null) {
                // 3. Limpa a tabela e mostra apenas o resultado encontrado
                modeloTabela.setNumRows(0);
                modeloTabela.addRow(new Object[]{
                e.getAluno().getMatricula(),
                e.getInstrutor().getName(),
                e.getDataAvaliacao(),
                e.getPeso(),
                e.getAltura(),
                e.getPercentualGordura(),
                e.getBiceps(),
                e.getCintura(),
                e.getOmbro(),
                e.getPanturrilha(),
                e.getCoxa(),
                e.getGluteo(),
                e.getPeitoral(),
                avaliacaoFisicaController.calcularImc(e.getAltura(), e.getPeso())
                });
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Avaliação Fisica não encontrada!");
            }
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao buscar: " + ex.getMessage());
        }
    } else if (matDigitada != null) {
        // Se o usuário clicou OK sem digitar nada, voltamos a listar todos
        atualizarTabela();
    }
    }//GEN-LAST:event_btnBusMatActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // 1. Verifica se tem alguém selecionado
    int linhaSelecionada = tblAvaliacaoFisica.getSelectedRow();
    
    if (linhaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um campo na tabela para editar.");
        return;
    }

    // 2. Pega a matricula e os dados atuais da tabela
    String matricula = (String) modeloTabela.getValueAt(linhaSelecionada, 0);
    String instrutor = (String) modeloTabela.getValueAt(linhaSelecionada, 1);
    LocalDate dataAvaliacao = (LocalDate) modeloTabela.getValueAt(linhaSelecionada, 2);
    float peso = (float) modeloTabela.getValueAt(linhaSelecionada, 3);
    int altura = (int) modeloTabela.getValueAt(linhaSelecionada, 4);
    float percentualGordura = (float) modeloTabela.getValueAt(linhaSelecionada, 5);
    int biceps = (int) modeloTabela.getValueAt(linhaSelecionada, 6);
    int cintura = (int) modeloTabela.getValueAt(linhaSelecionada, 7);
    int ombro = (int) modeloTabela.getValueAt(linhaSelecionada, 8);
    int panturrilha = (int) modeloTabela.getValueAt(linhaSelecionada, 9);
    int coxa = (int) modeloTabela.getValueAt(linhaSelecionada, 10);
    int gluteo = (int) modeloTabela.getValueAt(linhaSelecionada, 11);
    int peitoral = (int) modeloTabela.getValueAt(linhaSelecionada, 12);

    try {
        // 3. Abre caixinhas pedindo as novas informações (já sugere o nome atual)
        String novoInstrutor = javax.swing.JOptionPane.showInputDialog(this, "Nome do Instrutor:", instrutor);
        if (novoInstrutor == null) return; // Se cancelar, para aqui

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dataStr = JOptionPane.showInputDialog(this, "Data da Avaliação (dd/MM/yyyy):", dataAvaliacao.format(formatter));
        if (dataStr == null) return;

        LocalDate novaDataAvaliacao;
        try {
            novaDataAvaliacao = LocalDate.parse(dataStr, formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this,
                "Data inválida. Use o formato dd/MM/yyyy.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
        return;
        }

        String novoPesoStr = JOptionPane.showInputDialog(this, "Peso:", peso);
        if (novoPesoStr == null) return;

        float novoPeso;
        try {
            novoPeso = Float.parseFloat(novoPesoStr.replace(",", "."));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Peso inválido. Informe um número válido.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        String novaAlturaStr = JOptionPane.showInputDialog(this, "Altura (cm):", altura);
        if (novaAlturaStr == null) return;

        int novaAltura;
        try {
            novaAltura = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String novoPercentualGorduraStr = JOptionPane.showInputDialog(this, "Percentual de gordura:", percentualGordura);
        if (novoPercentualGorduraStr == null) return;

        float novoPercentualGordura;
        try {
            novoPercentualGordura = Float.parseFloat(novoPesoStr.replace(",", "."));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Percentual de gordura inválido. Informe um número válido.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        String novoBicepsStr = JOptionPane.showInputDialog(this, "Biceps:", biceps);
        if (novoBicepsStr == null) return;

        int novoBiceps;
        try {
            novoBiceps = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String novaCinturaStr = JOptionPane.showInputDialog(this, "Cintura:", cintura);
        if (novaCinturaStr == null) return;

        int novaCintura;
        try {
            novaCintura = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String novoOmbroStr = JOptionPane.showInputDialog(this, "Ombro:", ombro);
        if (novoOmbroStr == null) return;

        int novoOmbro;
        try {
            novoOmbro = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        String novaPanturrilhaStr = JOptionPane.showInputDialog(this, "Panturrilha:", panturrilha);
        if (novaPanturrilhaStr == null) return;

        int novaPanturrilha;
        try {
            novaPanturrilha = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        String novaCoxaStr = JOptionPane.showInputDialog(this, "Coxa:", coxa);
        if (novaCoxaStr == null) return;

        int novaCoxa;
        try {
            novaCoxa = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        String novoGluteoStr = JOptionPane.showInputDialog(this, "Gluteo:", gluteo);
        if (novoGluteoStr == null) return;

        int novoGluteo;
        try {
            novoGluteo = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }

        String novoPeitoralStr = JOptionPane.showInputDialog(this, "Peitoral:", peitoral);
        if (novoPeitoralStr == null) return;

        int novoPeitoral;
        try {
            novoPeitoral = Integer.parseInt(novaAlturaStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Informe um número inteiro.",
                "Erro",
            JOptionPane.ERROR_MESSAGE);
            return;
        }
        // 4. Busca o objeto original, atualiza e salva
        br.com.ifba.avaliacaofisica.entity.AvaliacaoFisica e = avaliacaoFisicaController.findByAluno_Matricula(matricula);
        
        e.getAluno().setMatricula(matricula);
        e.getInstrutor().setName(novoInstrutor);
        e.setDataAvaliacao(novaDataAvaliacao);
        e.setPeso(novoPeso);
        e.setAltura(novaAltura);
        e.setPercentualGordura(novoPercentualGordura);
        e.setBiceps(novoBiceps);
        e.setCintura(novaCintura);
        e.setOmbro(novoOmbro);
        e.setPanturrilha(novaPanturrilha);
        e.setCoxa(novaCoxa);
        e.setGluteo(novoGluteo);
        e.setPeitoral(novoPeitoral);

        avaliacaoFisicaController.update(e.getAluno().getMatricula(), e); // Ou .save(e), o Spring entende que é edição pela matricula

        // 5. Sucesso e atualização da tela
        javax.swing.JOptionPane.showMessageDialog(this, "Avaliação atualizada com sucesso!");
        atualizarTabela();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao editar: " + e.getMessage());
     }
    }//GEN-LAST:event_btnEditarActionPerformed
    //Método para mostrar a tabela de avaliação fisica
    public javax.swing.JTable getTabela() {
    return tblAvaliacaoFisica;
}

    public void atualizarTabela() {
    // Limpa a tabela antes de carregar
    modeloTabela.setNumRows(0);
    
   try {
        // Busca a lista no banco via controller
        java.util.List<br.com.ifba.avaliacaofisica.entity.AvaliacaoFisica> lista = avaliacaoFisicaController.findAll();
        
        // Adiciona cada exercício como uma linha na tabela
        for (br.com.ifba.avaliacaofisica.entity.AvaliacaoFisica e : lista) {
            modeloTabela.addRow(new Object[]{
                e.getAluno().getMatricula(),
                e.getInstrutor().getName(),
                e.getDataAvaliacao(),
                e.getPeso(),
                e.getAltura(),
                e.getPercentualGordura(),
                e.getBiceps(),
                e.getCintura(),
                e.getOmbro(),
                e.getPanturrilha(),
                e.getCoxa(),
                e.getGluteo(),
                e.getPeitoral(),
                avaliacaoFisicaController.calcularImc(e.getAltura(), e.getPeso())
            });
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar exercícios: " + e.getMessage());
    }
 }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliacaoFisicaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       //</editor-fold>
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaAvaliacaoFisicaListar().setVisible(true);
        });
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusMat;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovaAvlFis;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAvaliacaoFisica;
    // End of variables declaration//GEN-END:variables
}
