/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.aluno.view;


import br.com.ifba.Prg03ProjetoApplication;
import br.com.ifba.aluno.controller.AlunoController;
import br.com.ifba.aluno.entity.Aluno;
import br.com.ifba.aluno.repository.AlunoRepository;
import br.com.ifba.aluno.service.AlunoService;
import br.com.ifba.plano.repository.PlanoRepository;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

/**
 *
 * @author ETM-00168
 */
public class TelaListagemAlunos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaListagemAlunos.class.getName());
   
  private final AlunoController alunoController;
  private List<Aluno> listaCompleta;
  private List<Aluno> listaFiltrada; 
  private List<Aluno> alunosFiltrados = new ArrayList<>();
  
    /**
     * Creates new form TelaListagemAlunos
     * 
     */
    public TelaListagemAlunos() {
        initComponents();
            ApplicationContext context =
            new AnnotationConfigApplicationContext(Prg03ProjetoApplication.class);
         alunoController = context.getBean(AlunoController.class);
        CarregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();
        cmbFiltro = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnNotificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel1.setText("Listagem de Alunos");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Status", "Data Vencimento"
            }
        ));
        jScrollPane1.setViewportView(tblAlunos);

        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Ativos", "Vencidos", "Inativos" }));
        cmbFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFiltroActionPerformed(evt);
            }
        });

        jLabel2.setText("Total de Alunos:");

        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0");

        btnNotificar.setText("Notificar");
        btnNotificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNotificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lblTotal)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnNotificar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblTotal)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void CarregarTabela() {
    List<Aluno> alunos = alunoController.findAll();
    CarregarAlunos(alunos);
}

    private void CarregarAlunos(List<Aluno> alunos) {
   

   DefaultTableModel model = (DefaultTableModel) tblAlunos.getModel();
    model.setRowCount(0); // limpa a tabela antes de carregar

    for (Aluno aluno : alunos) {
         model.addRow(new Object[]{
            aluno.getName(),
            aluno.getCpf(),
            aluno.isStatus() ? "Ativo" : "Inativo",
            alunoController.getDataVencimento(aluno)
           
        });
    }
    lblTotal.setText("Total de Alunos listados: " + alunos.size());
}
private void aplicarFiltro() {

    String opcao = cmbFiltro.getSelectedItem().toString();

    List<Aluno> alunos = alunoController.findAll();
    List<Aluno> filtrados = new ArrayList<>();

    Date hoje = new Date();

    for (Aluno aluno : alunos) {

        Date vencimento = alunoController.getDataVencimento(aluno);

        switch (opcao) {

            case "Todos" -> filtrados.add(aluno);

            case "Ativos" -> {
                if (aluno.isStatus()) {
                    filtrados.add(aluno);
                }
            }

            case "Vencidos" -> {
                if (vencimento != null && vencimento.before(hoje)) {
                    filtrados.add(aluno);
                }
            }

            case "Inativos/Trancados" -> {
                if (!aluno.isStatus()) {
                    filtrados.add(aluno);
                }
            }
        }
    }
    //  guarda a lista filtrada para o botão usar
    alunosFiltrados = filtrados;
    //  atualiza a tabela
    CarregarAlunos(filtrados);
    //  habilita o botão SOMENTE se for "Vencidos"
    btnNotificar.setEnabled("Vencidos".equals(opcao));
}
  
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
        //pega uma linha selecionada
        int linhaSelecionada = tblAlunos.getSelectedRow();
        
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, 
                    "Selecione um aluno para editar!");
            return;
        }
        //pega os valores atuais
        String nomeAtual = tblAlunos.getValueAt(linhaSelecionada, 0).toString();
        String cpfAtual = tblAlunos.getValueAt(linhaSelecionada, 1).toString();
        String statusAtual = tblAlunos.getValueAt(linhaSelecionada, 2).toString();
        
        //Editando nome
        String novoNome = JOptionPane.showInputDialog(null, "editar Nome", nomeAtual);
        if (novoNome != null){
            tblAlunos.setValueAt(novoNome, linhaSelecionada, 0);
        }
        
        //Editando cpf
        String novoCpf = JOptionPane.showInputDialog(null, "editar cpf", cpfAtual);
        if (novoCpf != null){
            tblAlunos.setValueAt(novoCpf, linhaSelecionada, 1);   
        }
        
        //Editando Status
        String novoStatus = JOptionPane.showInputDialog(null, "editar status", statusAtual);
        if (novoStatus != null){
            tblAlunos.setValueAt(novoStatus, linhaSelecionada, 2);
        }
        
        CarregarTabela();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        
        //Chama a tela de matricula
        TelaMatriculaAlunos telaMatricula = new TelaMatriculaAlunos();
        telaMatricula.setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        
        //pega a linha seleionada
        int linhaSelecionada = tblAlunos.getSelectedRow();
        //caso nao selecionou nehuma linha, aparece a mensagem
        if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um aluno para excluir");
        return;
        }
        //pega o cpf do aluno da linha selecionada
        String cpfAluno = (String) tblAlunos.getValueAt(linhaSelecionada, 1);
        
        //confirma se realmente deseja excluir
        int confirmacao = JOptionPane.showConfirmDialog(this,
        "Deseja realmente excluir este aluno?",
        "Confirmação",
        JOptionPane.YES_NO_OPTION
);
//se for confirmado e tudo der certo, exclui e aparece a mensagem de secesso
if (confirmacao == JOptionPane.YES_OPTION) {
    
        alunoController.delete(cpfAluno);
        CarregarTabela();
        JOptionPane.showMessageDialog(this, "Aluno excluído com sucesso!");
    }//GEN-LAST:event_btnDeletarActionPerformed
    }
    
    private void cmbFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltroActionPerformed
        // TODO add your handling code here:
        aplicarFiltro();
        
    }//GEN-LAST:event_cmbFiltroActionPerformed

    private void btnNotificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificarActionPerformed
        // TODO add your handling code here:
        if (alunosFiltrados.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Não há alunos vencidos para notificar.");
        return;
    }

    JOptionPane.showMessageDialog(this,
            "Enviando notificações para " + alunosFiltrados.size() + " alunos...");

    for (Aluno aluno : alunosFiltrados) {
        alunoController.enviarEmail(aluno);
    }
    }//GEN-LAST:event_btnNotificarActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

    java.awt.EventQueue.invokeLater(() -> {
        TelaListagemAlunos tela = new TelaListagemAlunos();
        tela.setVisible(true);
    });

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNotificar;
    private javax.swing.JComboBox<String> cmbFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblAlunos;
    // End of variables declaration//GEN-END:variables
}
